import { BrandSettings, Client, Property, Technician, Ticket, Quote, Invoice, Message } from './types';

export const MOCK_BRAND: BrandSettings = {
  companyName: 'MainteQC Pro Services',
  logo: 'https://picsum.photos/seed/mainteqc/200/200',
  accentColor: '#2563eb',
  phone: '(555) 123-4567',
  email: 'support@mainteqc.com',
  businessHours: 'Mon-Fri 8am-6pm, Sat 9am-2pm',
  serviceCategories: ['Plumbing', 'Electrical', 'HVAC', 'Handyman'],
  address: '123 Service Way, Tech City, ST 12345',
  tagline: 'Quality Maintenance, Quantified Results.',
};

export const MOCK_CLIENTS: Client[] = [
  {
    id: 'c1',
    fullName: 'John Smith',
    email: 'john@example.com',
    phone: '(555) 111-2222',
    companyName: 'Smith Realty',
    billingAddress: '456 Billing Ave, Wealthy Hills, ST 90210',
    notes: 'Preferred client, always pays on time.',
    status: 'active',
    preferredContactMethod: 'email',
  },
  {
    id: 'c2',
    fullName: 'Sarah Johnson',
    email: 'sarah@example.com',
    phone: '(555) 333-4444',
    billingAddress: '789 Oak Lane, Suburban Grove, ST 54321',
    notes: 'New customer, referred by John.',
    status: 'active',
    preferredContactMethod: 'text',
  },
];

export const MOCK_PROPERTIES: Property[] = [
  {
    id: 'p1',
    clientId: 'c1',
    clientName: 'John Smith',
    nickname: 'Main Office',
    address: '100 Business Blvd',
    city: 'Tech City',
    state: 'ST',
    zip: '12345',
    propertyType: 'commercial',
    accessInstructions: 'Key code 1234 at front desk.',
    propertyNotes: 'Large HVAC system on roof.',
    petsOrOnsiteNotes: 'No pets.',
    parkingNotes: 'Park in designated visitor spots.',
    gateOrEntryNotes: 'Front desk security.',
  },
  {
    id: 'p2',
    clientId: 'c1',
    clientName: 'John Smith',
    nickname: 'Rental Unit A',
    address: '202 Maple St',
    city: 'Tech City',
    state: 'ST',
    zip: '12345',
    propertyType: 'residential',
    accessInstructions: 'Lockbox on side door code 9988.',
    propertyNotes: 'Older plumbing.',
    petsOrOnsiteNotes: 'Tenant has a small dog.',
    parkingNotes: 'Driveway parking.',
    gateOrEntryNotes: 'Side gate is sticky.',
  },
  {
    id: 'p3',
    clientId: 'c2',
    clientName: 'Sarah Johnson',
    nickname: 'Home',
    address: '789 Oak Lane',
    city: 'Suburban Grove',
    state: 'ST',
    zip: '54321',
    propertyType: 'residential',
    accessInstructions: 'Ring doorbell, someone is usually home.',
    propertyNotes: 'Smart home setup.',
    petsOrOnsiteNotes: 'Two cats, keep doors closed.',
    parkingNotes: 'Street parking available.',
    gateOrEntryNotes: 'None.',
  },
];

export const MOCK_TECHNICIANS: Technician[] = [
  {
    id: 't1',
    fullName: 'Mike Miller',
    email: 'mike@mainteqc.com',
    phone: '(555) 999-8888',
    specialties: ['Plumbing', 'Handyman'],
    status: 'available',
    notes: 'Lead plumber, 10 years experience.',
  },
  {
    id: 't2',
    fullName: 'Dave Davis',
    email: 'dave@mainteqc.com',
    phone: '(555) 777-6666',
    specialties: ['Electrical', 'HVAC'],
    status: 'busy',
    notes: 'Certified electrician.',
  },
];

const getRelativeDate = (daysOffset: number) => {
  const date = new Date();
  date.setDate(date.getDate() + daysOffset);
  return date.toISOString().split('T')[0];
};

export const MOCK_TICKETS: Ticket[] = [
  {
    id: 'tk1',
    title: 'Leaking Faucet in Kitchen',
    description: 'The main kitchen faucet is dripping constantly, wasting water.',
    category: 'Plumbing',
    urgency: 'medium',
    status: 'scheduled',
    clientId: 'c1',
    clientName: 'John Smith',
    propertyId: 'p1',
    propertyNickname: 'Main Office',
    serviceAddress: '100 Business Blvd, Tech City, ST 12345',
    preferredDate: getRelativeDate(1),
    preferredTime: 'Morning',
    scheduledDate: getRelativeDate(1),
    scheduledTime: '09:00',
    assignedTechnicianId: 't1',
    assignedTechnicianName: 'Mike Miller',
    contactPreference: 'email',
    adminNotes: 'Urgent for the client.',
    technicianNotes: '',
    completionNotes: '',
    createdAt: new Date().toISOString(),
    createdByEmail: 'john@example.com',
  },
  {
    id: 'tk2',
    title: 'AC Not Cooling',
    description: 'The air conditioning unit is running but not blowing cold air.',
    category: 'HVAC',
    urgency: 'high',
    status: 'pending_review',
    clientId: 'c2',
    clientName: 'Sarah Johnson',
    propertyId: 'p3',
    propertyNickname: 'Home',
    serviceAddress: '789 Oak Lane, Suburban Grove, ST 54321',
    preferredDate: getRelativeDate(0),
    preferredTime: 'Afternoon',
    contactPreference: 'text',
    adminNotes: '',
    technicianNotes: '',
    completionNotes: '',
    createdAt: new Date().toISOString(),
    createdByEmail: 'sarah@example.com',
  },
  {
    id: 'tk3',
    title: 'Outlet Sparking',
    description: 'The outlet in the master bedroom sparked when I plugged in a lamp.',
    category: 'Electrical',
    urgency: 'emergency',
    status: 'in_progress',
    clientId: 'c1',
    clientName: 'John Smith',
    propertyId: 'p2',
    propertyNickname: 'Rental Unit A',
    serviceAddress: '202 Maple St, Tech City, ST 12345',
    preferredDate: getRelativeDate(0),
    preferredTime: 'ASAP',
    scheduledDate: getRelativeDate(0),
    scheduledTime: '02:00 PM',
    assignedTechnicianId: 't2',
    assignedTechnicianName: 'Dave Davis',
    contactPreference: 'phone',
    adminNotes: 'Safety hazard!',
    technicianNotes: 'Arrived on site, investigating wiring.',
    completionNotes: '',
    createdAt: new Date().toISOString(),
    createdByEmail: 'john@example.com',
  },
  {
    id: 'tk4',
    title: 'Toilet Clogged',
    description: 'Guest bathroom toilet is backed up.',
    category: 'Plumbing',
    urgency: 'medium',
    status: 'completed',
    clientId: 'c1',
    clientName: 'John Smith',
    propertyId: 'p2',
    propertyNickname: 'Rental Unit A',
    serviceAddress: '202 Maple St, Tech City, ST 12345',
    preferredDate: getRelativeDate(-1),
    preferredTime: 'Morning',
    scheduledDate: getRelativeDate(-1),
    scheduledTime: '10:00 AM',
    assignedTechnicianId: 't1',
    assignedTechnicianName: 'Mike Miller',
    contactPreference: 'email',
    adminNotes: '',
    technicianNotes: 'Cleared clog with auger.',
    completionNotes: 'All clear, tested multiple flushes.',
    createdAt: new Date(Date.now() - 86400000).toISOString(),
    createdByEmail: 'john@example.com',
    invoiceStatus: 'paid',
  },
];

export const MOCK_QUOTES: Quote[] = [
  {
    id: 'q1',
    ticketId: 'tk2',
    clientId: 'c2',
    propertyId: 'p3',
    status: 'draft',
    lineItems: [
      { description: 'AC Diagnostic Fee', quantity: 1, rate: 85, total: 85 },
      { description: 'Refrigerant Recharge (lb)', quantity: 2, rate: 120, total: 240 },
    ],
    subtotal: 325,
    tax: 26,
    total: 351,
    notes: 'Estimate based on initial description.',
  },
];

export const MOCK_INVOICES: Invoice[] = [
  {
    id: 'i1',
    ticketId: 'tk4',
    clientId: 'c1',
    propertyId: 'p2',
    status: 'paid',
    lineItems: [
      { description: 'Plumbing Service Call', quantity: 1, rate: 150, total: 150 },
    ],
    subtotal: 150,
    tax: 12,
    total: 162,
    dueDate: getRelativeDate(7),
    paidDate: getRelativeDate(-1),
    paymentMethod: 'Credit Card',
    notes: 'Thank you for your business!',
  },
];

export const MOCK_MESSAGES: Message[] = [
  {
    id: 'm1',
    senderId: 'admin',
    senderRole: 'ADMIN',
    recipientId: 'c1',
    recipientRole: 'CLIENT',
    text: 'Your request for the kitchen faucet has been scheduled for tomorrow.',
    ticketId: 'tk1',
    timestamp: new Date(Date.now() - 3600000).toISOString(),
    read: true,
  },
  {
    id: 'm2',
    senderId: 'c1',
    senderRole: 'CLIENT',
    recipientId: 'admin',
    recipientRole: 'ADMIN',
    text: 'Great, thank you for the quick response!',
    ticketId: 'tk1',
    timestamp: new Date(Date.now() - 1800000).toISOString(),
    read: false,
  },
];
